ALTER TABLE users
    ADD COLUMN password_hash VARCHAR(255) NOT NULL CHECK (password_hash <> '') DEFAULT 'PLACEHOLDER',
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE users ALTER COLUMN password_hash DROP DEFAULT;
